export const GET_COUNTRIES_ENDPOINT = "https://api.first.org/data/v1/countries";
export const SETTINGS = "Settings";
export const USERS_LIST = "Users List";
export const PLUS = "+";
export const ADD_NEW_USER = "Add New User";
export const ADD_USER = "Add User";
export const ACTIVE = "Active";
export const INACTIVE = "Inactive";
export const ACTIONS = "Actions";
export const ALT_IMAGE = "No preview";
export const REMOVE = "Remove";
export const REQUIRED_FIELD_MESSAGE = "Required Field"